global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
scrape_configs:
  - job_name: user-feedback
    honor_timestamps: true
    metrics_path: management/prometheus
    scrape_interval: 5s
    scheme: http
    static_configs:
      - targets: ["host.docker.internal:8080"]
